apps/app/src/electron/storageHandler.ts

Fixes persisting data on Linux.
On some Linux distributions the `Documents` folder may exist, however, the recommendation of the Linux FHS is to create a directory starting with `.` for application data storage[1], as the exact structure of the home directory has not been standardised by Linux.
This PR will change the `baseFolder` for storage to the equivalent of `$HOME/.super-conductor`, which should work for most users.
[1] See `3.8.2` https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s08.html#ftn.idm236092760560

fix: Data storage on Linux

---

apps/app/package.json

Fixes an issue when starting SuperConductor whereby sharp is unable to find libvips.
I've tested this on a fresh install of Ubuntu 20.04, but not on Windows or Mac.

fix: Copy libraries from sharp into final bundle

---

shared/packages/tsr-bridge/src/TSR.ts

Maybe there's a better way to do this but this was all I could think of in the moment.

fix: don't show a connection warning for UDP OSC devices

---

apps/app/src/lib/TSR.ts
apps/app/src/lib/TimelineObj.ts
apps/app/src/react/components/rundown/GroupView/TimelineObject.tsx
apps/app/src/react/components/sidebar/timelineObj/timelineObjs/atem.tsx
apps/app/src/react/components/sidebar/timelineObj/timelineObjs/casparcg.tsx
apps/app/src/react/components/sidebar/timelineObj/timelineObjs/osc.tsx
apps/app/src/react/components/sidebar/timelineObj/timelineObjs/vMix.tsx
apps/app/src/react/styles/layer.scss
apps/app/src/react/styles/settings.scss

closes #37 
This PR adds support for CasparCG transitions to the GUI.
TODO:

feat: add support for CasparCG transitions

---

apps/app/src/react/App.tsx

This PR adds a window-wide hotkey for Escape to clear the current selection, if no input is selected and no pop-over/dialog open.

fix: blur current selection on Escape

---

apps/app/package.json
apps/app/src/electron/IPCServer.ts
apps/app/src/electron/SuperConductor.ts
apps/app/src/electron/storageHandler.ts
apps/app/src/electron/telemetry.ts
apps/app/src/ipc/IPCAPI.ts
apps/app/src/lib/userAgreement.ts
apps/app/src/models/App/AppData.ts
apps/app/src/react/App.tsx
apps/app/src/react/api/IPCServer.ts
apps/app/src/react/components/UserAgreementScreen.tsx
apps/app/src/react/components/util/Debug.tsx
apps/app/src/react/components/util/ErrorBoundary.tsx
apps/app/src/react/mobx/AppStore.ts

This PR adds two new things:
**Crash / Error Reporting and statistics**
SuperConductor will send reports to a SuperFly.tv-database upon startup and upon an error/crash. The reason for this is to catch and fix errors that happen out there in the wild.
If needed, it is possible to opt out by adding the `--disable-telemetry` CLI argument.
I've also made the code that handles receival of the data public [here](https://github.com/SuperFlyTV/superconductor-telemetry), if anyone's curious.
**User Agreement**
It is important that the user understands that the application sends usage reports. Therefore, I've added a User Agreement-splash screen that the user will have to accept in order to use the application.

Feat: Add Error Reporting & User Agreement

---

apps/app/src/react/components/headerBar/deviceStatuses/ConnectionStatus.tsx
apps/app/src/react/components/pages/homePage/scList/style.scss
apps/app/src/react/styles/connection-status.scss
apps/app/src/react/styles/foundation/_colors.scss

This PR makes the device statuses in the top header more readable by adding a pill-shaped dark background and lightening the text colors. This gives both the red and green colors a contrast ratio >= 7.0, making them meet WCAG AAA standards for legibility. This PR also unifies the colors used in the top header and on the Bridges page.

fix: improve the readability of device statuses in the top header

---

apps/app/src/electron/IPCServer.ts
apps/app/src/lib/util.ts

This PR amends the `copyPart` method to use the `generateNewTimelineObjIds` when copying a timeline. This ensures that any `enable` references to other timelineObjs are still functional in the copied output. Additionally, this PR reduces a bit of code duplication by using `copyGroup` and `copyPart` in some additional places.

fix: prevent timeline references from breaking when copying groups or parts using the clipboard

---

apps/app/src/react/components/sidebar/timelineObj/timelineObjs/lib.tsx

This PR makes two small changes to the timeline object inspector:
1. It removes the Device Type dropdown because it caused more bugs than it solved. Properly implementing this dropdown would require substantial effort and guesswork, so we're putting it aside for now.
2. It ensures that only valid layers are present in the Layer dropdown.

fix: prevent invalid timelineobj changes

---

apps/app/src/lib/TimelineObj.ts
apps/app/src/react/components/sidebar/timelineObj/timelineObjs/casparcg.tsx

This removes the transitions from CasparCG Templates, since they aren't really supported by CasparCG anyway.
This also fixes an issue where when stopping a Template the wrong command is sent (a PLAY "empty" instead of a CG STOP).
closes #101

Fix: CasparCG template transitions

---

apps/app/src/lib/util.ts
apps/app/src/react/components/inputs/Btn/style.scss
apps/app/src/react/components/inputs/ToggleBtn/style.scss
apps/app/src/react/components/sidebar/SidebarContent.tsx
apps/app/src/react/components/sidebar/SidebarResourceLibrary.tsx
apps/app/src/react/components/util/SmallCheckbox.tsx
apps/app/src/react/mobx/GuiStore.ts
apps/app/src/react/styles/foundation/_variables.scss
apps/app/src/react/styles/group.scss
apps/app/src/react/styles/layer.scss
apps/app/src/react/styles/part.scss
apps/app/src/react/styles/sidebar/sidebar.scss
apps/app/src/react/styles/trigger.scss

This PR adds a new, expandable filter that allows filtering both on Device and Resource Type.
Also, the styling for the filters and resource library was refactored a little for simplicity.
Also, added a clear button for the name filter.
Also, cleaned up the styles a little bit.
I think this resolves: https://github.com/SuperFlyTV/SuperConductor/issues/99

feat: allow filtering per Resource Type

---

apps/app/src/react/components/sidebar/timelineObj/timelineObjs/casparcg.tsx

This PR fixes an issue where changing the "Type" dropdown of a CasparCG timeline object would cause data corruption and UI crashes. Of note is that we still only support the `MEDIA` and `TEMPLATE` types -- the rest result in gray timelineObjs that display a raw ID, as shown below:
Closes #119

fix: don't corrupt data when changing the type of a CasparCG timeline obj

---

apps/app/package.json
apps/tsr-bridge/package.json
package.json
shared/packages/peripherals/package.json
shared/packages/peripherals/src/peripherals/midi.ts
yarn.lock

I think this fixes a bug in the mac and linux builds, as it looks like the sharp libs in the latest builds will be missing, due to it trying to bundle the wrong versions.
I haven't tested any of this, but I don't think it will cause any problems

chore: dependency cleanup

---

apps/app/tsconfig.json

I got an error that said the apps/app project could not write .d.ts fils to dist/, as dist/ would then be added back into the source of the project again.
I haven't researched the problem/solution again. Since I didn't see any explicit include-property in the tsconfig, I ended up just blindly excluding dist/, and the error went away.
Not testet/qualified in any other way. I might be wrong here.

Fix: app tsconfig exclude dist

---

apps/app/src/electron/IPCServer.ts
apps/app/src/ipc/IPCAPI.ts
apps/app/src/models/rundown/Group.ts
apps/app/src/react/api/IPCServer.ts
apps/app/src/react/components/rundown/GroupView/GroupView.tsx
apps/app/src/react/mobx/GuiStore.ts

This PR allows the "collapsed" state of a group to be persisted to disk such that it is restored on application startup.
Helps #135

feat: persist group collapsed state

---

apps/app/src/react/components/rundown/GroupView/GroupView.tsx
apps/app/src/react/styles/group.scss

Simple implementation, open to feedback and fine tuning:
Helps #135, will conflict with #146 once it is merged due to this PR using the `groupCollapsed` var, which is removed by #146. Will be trivial to fix, just giving a heads up.

feat: show a summary on collapsed groups

---

apps/app/src/lib/playout/__tests__/preparedGroupPlayData.test.ts
apps/app/src/lib/playout/preparedGroupPlayData.ts

This PR fixes two small issues with looping Parts in looping Groups in Single mode (one Part at a time), with auto-step:
1. In a looping Group, when Part A has looping enabled: After stepping to Parts B, C, and so on, the group would stop at the last part, instead of returning back to Part A.
2. In a looping Group, when Part B has looping enabled: After stepping to Parts C, D, and so on, the group would return back to Part A and loop that part instead of Part B.
Edit:
It also fixes an issue with looping Group in Single mode without auto-step:
3. Started Part was played out twice and then auto-stepping throughout the rest of the parts occurred instead of stopping after that part.

fix: small looping bugs

---

.gitignore
.vscode/launch.json
apps/app/nodemon.json

This PR enables debugging of the main Electron process of the dev build and adds launch configuration for attaching from VS Code. I think it's fine to have it always enabled in development mode, but if you think it should be optional, I will make it so.
Note: I'm not sure why lines 1-17 of .gitignore registered as changed. It could be the line endings.

chore: enable inspector for Electron in dev mode

---

apps/app/package.json
apps/app/src/electron/IPCServer.ts
apps/app/src/lib/util.ts
apps/app/src/react/components/sidebar/timelineObj/timelineObjs/httpSend.tsx
yarn.lock

This PR fixes three issues around `EditTimelineObjHTTPSendAny`
1. unwanted `_1` was appended to keys that were not duplicates, when the Key input was focused and un-focused without making a change
2. renamed or deleted parameters were kept as `undefined`, making the parameter count and numbering inaccurate
3. if _n_ parameters were defined, and one of them was named _param\<n\>_, it would get overwritten when adding a new parameter
Note: using deepmerge-ts with customized record merging was the cleanest thing I could come up with. Alternatively we could just stringify and parse those objects to have `undefined` removed, or avoid passing `undefined` between renderer and main process, and instead use some other way of marking properties to delete.

fix: HTTP Send parameter key issues

---

apps/app/src/lib/__tests__/util.test.ts
apps/app/src/lib/util.ts

There is a bug when adding a row to a table in GDD data.

Fix: bug in deep extend removing undefined

---

apps/app/src/electron/bridgeHandler.ts
shared/packages/tsr-bridge/src/TSR.ts

This improves on how we handle reconfiguring devices and re-connection of Bridges.
The issue from https://github.com/SuperFlyTV/SuperConductor/issues/64 is definitely less severe. In some rare cases I the list still does not populate immediately, but pressing the "Refresh all resources" button solves it.
This also fixes an issue that caused an incoming Bridge to not accept any settings changes after re-connecting due to storing references to the already disconnected instances with that same Id.
This should make removal of devices more robust by using the AbortController, however there are still some edge cases there.

fix: make bridge and device initialization more robust

---

apps/app/package.json
apps/app/src/electron/ClientEventBus.ts
apps/app/src/electron/EverythingService.ts
apps/app/src/electron/SuperConductor.ts
apps/app/src/electron/UndoService.ts
apps/app/src/electron/api/ApiServer.ts
apps/app/src/electron/api/ProjectService.ts
apps/app/src/ipc/IPCAPI.ts
apps/app/src/lib/__tests__/util.test.ts
apps/app/src/lib/util.ts
apps/app/src/main.ts
apps/app/src/models/project/Project.ts
apps/app/src/preload.ts
apps/app/src/react/App.tsx
apps/app/src/react/api/ApiClient.ts
apps/app/src/react/api/ElectronApi.ts
apps/app/src/react/api/RealtimeDataProvider.ts
apps/app/src/react/components/headerBar/deviceStatuses/DeviceStatuses.tsx
apps/app/src/react/components/pages/homePage/HomePage.tsx
apps/app/src/react/mobx/AnalogStore.ts
apps/app/src/react/mobx/AppStore.ts
apps/app/src/react/mobx/GDDValidatorStoreStore.ts
apps/app/src/react/mobx/GroupPlayDataStore.ts
apps/app/src/react/mobx/GuiStore.ts
apps/app/src/react/mobx/ResourcesAndMetadataStore.ts
tsconfig.build.json
yarn.lock

Addresses https://github.com/SuperFlyTV/SuperConductor/issues/174,
Makes undo/redo scoped to one of: current rundown, application (home), peripheral devices - depending on which section of the UI is active.
Disables `nodeIntegration` and enables `contextIsolation` for the main Electron app.

refactor: undo/redo

---

apps/app/src/react/components/headerBar/tabs/Tabs.tsx
apps/app/src/react/components/headerBar/tabs/tab/Tab.tsx

To follow global UX conventions. Try clicking any tabs in any other app to verify the convention.

fix: changes rundown-tab selection from onClick to onMouseDown
